version: '3.3'

# Defining the compose version
services:

#  nginx:
#   build: ./nginx
#   ports:
#     - 8687:80
#   depends_on:
#     - myproject
#   restart: "always"
 
 myproject:
  build: .
  command: sh -c "gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"
  expose: 
   - 8000
  restart: "always"