from django.urls import path
from .filter import *
from .views import *
urlpatterns = [
    path('Get-Categories/', GetCategories.as_view()),
    path('Get-Stores/', GetStores.as_view()),
    path('Get-AllProduct/', GetAllProduct.as_view()),
    path('Get-SubCategoryByCategory/<int:id>', GetSubCategory.as_view()),
    path('Get-ProductByCategory/<int:id>', ProductByCategory.as_view()),
    path('Get-ProductBySubCategory/<int:id>', ProductBySubCategory.as_view()),
    path('Get-StoreByCity/<int:id>', StoreByCities.as_view()),
    path('Get-News/', GetNews.as_view()),
    path('Get-Dispensaries/', GetAllDispensaries.as_view()),
    path('Get-Delivery/', GetAllDelivery.as_view()),
    path('Get-DispensaryByid/<int:id>',GetDispensaryByid.as_view()),
    path('Get-SortingFilterAtoZ/<int:id>',SortingFilter.as_view()),
    path('Get-ProductAccordingToDispensaries/<int:id>',ProductAccordingToDispensaries.as_view()),
    path('Get-ProductById/<int:id>',GetProductById.as_view()),
    path('CategoryOnProduct/',CategoryOnProduct.as_view()),
    path('Get-StrainType/',GetStrainType.as_view()),
    path('Get-ProductbyBrand/<int:id>',GetProductbyBrand.as_view()),
    path('Get-FilterBrand/',GetFilterBrand.as_view()),    
    path('Login/',Login.as_view()),
    path('ForgetPasswordAPI/',ForgetPasswordAPI.as_view()),
    path('ValidateOTPForgetPassword/',ValidateOTPForgetPassword.as_view()),
    path('VerifyOtpForgetPassword/',VerifyOtpForgetPassword.as_view()),
    path('RegisterAPI/',RegisterAPI.as_view()),
    path('ResetPassword/',ResetPassword.as_view()),
    path('Get-SearchFilter/',ProductListView.as_view()),
    path('Get-ProductByCategorybyStore/<int:id>',ProductByCategorybyStore.as_view()),
    path('Get-Addtocart/',GetAddtocart.as_view()),
    path('Add-AddtoCart/',AddAddtoCart.as_view()),
    path('Update-AddtoCart/<int:id>',UpdateAddtoCart.as_view()),
    path('DeleteAddtoCart/<int:id>',DeleteAddtoCart.as_view()),
    path('Get-Order/',GetOrder.as_view()),
    path('Add-Order/',AddOrder.as_view()),
    path('Update-Order/<int:id>',UpdateOrder.as_view()),
    path('Delete-Order/<int:id>',DeleteOrder.as_view()),
    path('ClearAddtoCart/',ClearAddtoCart.as_view()),
    path('Get-AddtoCartImage/<int:id>',GetAddtoCartImage.as_view()),
    path('Update-Order/<int:id>',UpdateOrder.as_view()),
    path('Delete-Order/<int:id>',DeleteOrder.as_view()),
    path('Get-DeliveryStores/',GetDeliveryStores.as_view()),
    path('Get-PickupStores/',GetPickupStores.as_view()),
    #################################################################################################################################################
    path('Get-Wishlist/',GetWishList.as_view()),
    path('Add-Wishlist/',AddWishList.as_view()),
    path('Update-Wishlist/<int:id>',UpdateWishList.as_view()),
    path('Delete-Wishlist/<int:id>',DeleteWishList.as_view()),
    #####################################################################################
    path('Get-AllSubCategory/',AllSubCategory.as_view()),
    path('Get-AllBrand/', GetBrand.as_view()),
    path('Get-CategoryByStore/',CategoryByStore.as_view()),
    path('Get-filterSubcategorybyStoreandCategory/',filterSubcategorybyStoreandCategory.as_view()),
    path('Get-filterProductbyStoreandSubCategory/',filterProductbyStoreandSubCategory.as_view()),
    path('Get-filterProductbyStoreandCategory/',filterProductbyStoreandCategory.as_view()),
    path('Get-HomePageFilter/',HomePageFilter.as_view()),
    path('GoogleView/',GoogleView.as_view()),
    path('Get-AllHomePageBanner/',AllHomePageBanner.as_view()),
    path('Get-ResultHomeSearchFilter/',ResultHomeSearchFilter.as_view()),
    path('Get-BrandById/<int:id>',GetBrandById.as_view()),
    path('Get-StoreById/<int:id>', GetStoreById.as_view()),
    #################################################################################################################################################
    path('Get-Review/<int:id>',GetReview.as_view()),
    path('Add-Review/',AddReview.as_view()),
    path('Update-Review/<int:id>',UpdateReview.as_view()),
    path('Delete-Review/<int:id>',DeleteReview.as_view()),
    #################################################################################################################################################
    path('Get-Comment/',GetComment.as_view()),
    path('Add-Comment/',AddComment.as_view()),
    path('Delete-Comment/<int:id>',DeleteComment.as_view()),
    path('FacebookSignInView/',FacebookSignInView.as_view()),
    path('Get-DeliveryAddress/<int:id>',DeliveryAddress.as_view()),
    path('Get-PromotionalBanners/',GetPromotionalBanners.as_view()),
    path('Get-GetDeliveryCheck/',GetDeliveryCheck.as_view()),
    path('Get-CountProductAccordingToCategory/<int:id>',CountProductAccordingToCategory.as_view()),
    path('Get-GetNewsById/<int:id>', GetNewsById.as_view()),
    path('Update-UpdateUserProfile/', UpdateUserProfile.as_view()),
    path('Get-GetUserProfile/',GetUserProfile.as_view()),
    path('PromoCodeCheck/',PromoCodeCheck.as_view()),
    path('Get-GetDeliveryStoresHomepage/',GetDeliveryStoresHomepage.as_view()),
    path('Get-GetPendingOrder/',GetPendingOrder.as_view()),
    path('Get-GetDeliveredOrder/',GetDeliveredOrder.as_view()),
    path('Get-GetCancelOrder/',GetCancelOrder.as_view()),
    path('Get-GetProcessingOrder/',GetProcessingOrder.as_view()),
    path('Get-GetOrderBYID/<int:id>',GetOrderBYID.as_view()),
    path('Get-Dispensary_Product/',GetDispensary_Product.as_view()),
    path('Get-getReviewbyId/<int:id>/<int:productId>',getReviewbyId.as_view()),
    path('Get-AverageReviewAndRating/<int:id>',AverageReviewAndRating.as_view()),
    path('Get-AllUser/',AllUser.as_view()), 
    #################################################################################################################################################
    path('Get-GetBlankImage/',GetBlankImage.as_view()),
    path('Add-BlankImage/',AddBlankImage.as_view()),
    path('Update-BlankImage/<int:id>',UpdateBlankImage.as_view()),
    path('Delete-BlankImage/<int:id>',DeleteBlankImage.as_view()),
    #################################################################################################################################################
    path('Get-BlogLike/',GetBlogLike.as_view()),
    path('Add-BlogLike/',AddBlogLike.as_view()),
    path('Add-BlogView/<int:id>',AddBlogView.as_view()),
    path('HighPriceToLowPrice/<int:id>',HighPriceToLowPrice.as_view()),
    path('FilterDispensaries/',FilterDispensaries.as_view()),
    path('Add-Subscribe/',AddSubscribe.as_view()),
    path('Add-UserProfileOrderDetails/',AddUserProfileOrderDetails.as_view()),
    path('Get-UserProfileOrderDetails/',GetUserProfileOrderDetails.as_view()),
    path('BuyXGetYDiscount/',BuyXGetYDiscount.as_view()),
    path('Get-PopularStrain/',PopularStrain.as_view()),
    path('PriceFilter/',PriceFilter.as_view()),
    #################################################################################################################################################
    path('Get-SiteMap/',GetSiteMap.as_view()),
    path('Add-SiteMap/',AddSiteMap.as_view()),
    path('Update-SiteMap/<int:id>',UpdateSiteMap.as_view()),
    path('Delete-SiteMap/<int:id>',DeleteSiteMap.as_view()),
    path('Get-SitemapbyId/<int:id>',getSitemapbyId.as_view()),
    path('Get-ProductByStoreAndBrand/<int:store>/<int:brand>',GetProductByStoreAndBrand.as_view()),
    path('Get-BrandByStore/<int:id>',GetBrandByStore.as_view()),
    path('ProductFilterByWeightandStore/',ProductFilterByWeightandStore.as_view()),
    path('ProductFilterByUnitandStore/',ProductFilterByUnitandStore.as_view()),
    path('StrainFilterProduct/',StrainFilterProduct.as_view()),
    path('Delete-StoreReview/<int:id>',DeleteStoreReview.as_view()),
    path('Get-GetTest/',GetTest.as_view()),
    path('Add-Test/',AddTest.as_view()),
    # path('AddandUpdateHelpfullButton/',AddandUpdateHelpfullButton.as_view()),
    path('Get-Net_Weight/',GetNet_Weight.as_view()),
    # path('Get-HelfullButton/',GetHelfullButton.as_view()),
    path('WeightFilter/',WeightFilter.as_view()),
    path('Add-Helpfull/',AddHelpfull.as_view()),
    path('Get-StoreReview/<int:id>',GetStoreReview.as_view()),


]

