# Generated by Django 4.1.3 on 2024-02-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Roles",
            field=models.ManyToManyField(blank=True, to="AdminPanel.customrole"),
        ),
    ]
