# Generated by Django 4.1.3 on 2024-01-19 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 19, 5, 15, 40, 119348)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Vendor", "Vendor"),
                    ("Customer", "Customer"),
                ],
                default="Admin",
                max_length=30,
            ),
        ),
    ]
