# Generated by Django 4.2.4 on 2023-10-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Logo", models.ImageField(upload_to="media/Logo")),
                ("AboutUs1", models.ImageField(upload_to="media/AboutUs1")),
                ("AboutUs2", models.ImageField(upload_to="media/AboutUs2")),
                ("AboutUs3", models.ImageField(upload_to="media/AboutUs3")),
                ("AboutUs4", models.ImageField(upload_to="media/AboutUs4")),
                ("ShareImage", models.ImageField(upload_to="media/ShareImage")),
                (
                    "Fourhundredfour",
                    models.ImageField(upload_to="media/Fourhundredfour"),
                ),
                (
                    "Fourhundredthree",
                    models.ImageField(upload_to="media/Fourhundredthree"),
                ),
                (
                    "Fivehundredthree",
                    models.ImageField(upload_to="media/Fivehundredthree"),
                ),
                ("blogbanner", models.ImageField(upload_to="media/blogbanner")),
                ("Indica", models.ImageField(upload_to="media/Strain")),
                ("Hybrid", models.ImageField(upload_to="media/Strain")),
                ("Sativa", models.ImageField(upload_to="media/Strain")),
                ("CBD", models.ImageField(upload_to="media/Strain")),
            ],
        ),
    ]
