# Generated by Django 4.1.3 on 2024-01-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stores",
            name="License_Type",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Adult-Use Cultivation", "Adult-Use Cultivation"),
                    ("Adult-Use Mfg.", "Adult-Use Mfg."),
                    ("Adult-Use Nonstorefront", "Adult-Use Nonstorefront"),
                    ("Adult-Use Retail", "Adult-Use Retail"),
                    ("Distributor", "Distributor"),
                    ("Event", "Event"),
                    ("Medical Cultivation", "Medical Cultivation"),
                    ("Medical Mfg.", "Medical Mfg."),
                    ("Medical Nonstorefront", "Medical Nonstorefront"),
                    ("Medical Retail", "Medical Retail"),
                    ("Microbusiness", "Microbusiness"),
                    ("Testing Lab", "Testing Lab"),
                ],
                default="None",
                max_length=230,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stores",
            name="Store_Type",
            field=models.CharField(
                choices=[
                    ("dispensary", "Dispensary"),
                    ("delivery", "Delivery"),
                    ("Curbside Pickup", "Curbside Pickup"),
                ],
                default=None,
                max_length=150,
                null=True,
            ),
        ),
    ]
