# Generated by Django 4.1.3 on 2024-01-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0003_alter_stores_license_type_alter_stores_store_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stores",
            name="Stores_MobileNo",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
