# Generated by Django 4.1.3 on 2024-01-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0003_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Roles",
            field=models.ManyToManyField(blank=True, to="AdminPanel.customrole"),
        ),
    ]
