# Generated by Django 4.1.3 on 2024-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="RemovedNotification",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="stores",
            name="Store_Type",
            field=models.CharField(
                choices=[
                    ("dispensary", "Dispensary"),
                    ("delivery", "Delivery"),
                    ("Curbside Pickup", "Curbside Pickup"),
                ],
                default="dispensary",
                max_length=150,
                null=True,
            ),
        ),
    ]
