# Generated by Django 4.1.3 on 2024-01-12 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0004_alter_stores_stores_mobileno"),
    ]

    operations = [
        migrations.AddField(
            model_name="customrole",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
