# Generated by Django 4.1.3 on 2024-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0004_user_removednotification_alter_stores_store_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otpvalidate",
            field=models.BooleanField(default=True),
        ),
    ]
