# Generated by Django 4.1.3 on 2024-03-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0005_user_otpvalidate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otpvalidate",
            field=models.BooleanField(default=False),
        ),
    ]
