# Generated by Django 4.1.3 on 2024-01-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0005_customrole_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customrole",
            name="created_at",
        ),
    ]
