# Generated by Django 4.1.3 on 2024-01-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0006_remove_customrole_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
