# Generated by Django 4.1.3 on 2024-01-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserPanel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="DeliveryTime",
            field=models.CharField(max_length=200),
        ),
    ]
