# Generated by Django 4.1.3 on 2024-02-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserPanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="City",
            field=models.CharField(default="New York", max_length=256),
        ),
        migrations.AddField(
            model_name="order",
            name="Country",
            field=models.CharField(default="USA", max_length=256),
        ),
        migrations.AddField(
            model_name="order",
            name="State",
            field=models.CharField(default="New York", max_length=256),
        ),
    ]
