# Generated by Django 4.1.3 on 2024-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserPanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addtocart",
            name="City",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="addtocart",
            name="Country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="addtocart",
            name="State",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
