# Generated by Django 4.1.3 on 2024-01-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserPanel", "0002_alter_order_deliverytime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofileorderdetails",
            old_name="email",
            new_name="Email",
        ),
    ]
