# Generated by Django 4.1.3 on 2024-02-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserPanel", "0002_order_city_order_country_order_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="City",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="order",
            name="Country",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="order",
            name="State",
            field=models.CharField(max_length=256),
        ),
    ]
