# Generated by Django 4.1.3 on 2024-02-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserPanel", "0003_alter_order_city_alter_order_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("Customer", "Customer")],
                        default="Customer",
                        max_length=30,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="media/BlankImage.jpg",
                        null=True,
                        upload_to="media/UserProfile",
                    ),
                ),
                ("googlelink", models.URLField(null=True)),
                ("Name", models.CharField(max_length=999, null=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("MobilePhone", models.CharField(max_length=20, null=True)),
                ("password", models.CharField(max_length=1000)),
                ("DeliveryAddress", models.CharField(max_length=5000, null=True)),
                ("MedicalCardNumber", models.CharField(max_length=50, null=True)),
                ("MedicalCardExpire", models.DateField(null=True)),
                ("MedicalCardState", models.CharField(max_length=100, null=True)),
                ("EmailBoolean", models.BooleanField(default=False)),
                ("NewsLetter", models.BooleanField(default=False)),
                ("ReviewSuggestions", models.BooleanField(default=False)),
                ("PushNotification", models.BooleanField(default=False)),
                ("Recommendations", models.BooleanField(default=False)),
                ("Savings", models.BooleanField(default=False)),
                ("OrderupdatePushNotification", models.BooleanField(default=False)),
                ("OrderupdateSMSNotifications", models.BooleanField(default=False)),
                (
                    "DateOfBirth",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("otp", models.IntegerField(default=None, null=True)),
                (
                    "PhotoId",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="media/PhotoId"
                    ),
                ),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "MALE"), ("F", "FEMALE")],
                        default=None,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Hide", "Hide")],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
