# Generated by Django 4.1.3 on 2024-02-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UserPanel", "0004_customeruser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addtocart",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UserPanel.customeruser",
            ),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="UserPanel.customeruser"
            ),
        ),
        migrations.AlterField(
            model_name="bloglike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="UserPanel.customeruser"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UserPanel.customeruser",
            ),
        ),
        migrations.AlterField(
            model_name="recentview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="UserPanel.customeruser"
            ),
        ),
        migrations.AlterField(
            model_name="replyonstorereview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="UserPanel.customeruser"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="UserPanel.customeruser"
            ),
        ),
        migrations.AlterField(
            model_name="storereview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="UserPanel.customeruser"
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UserPanel.customeruser",
            ),
        ),
        migrations.AlterField(
            model_name="userprofileorderdetails",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="UserPanel.customeruser"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UserPanel.customeruser",
            ),
        ),
    ]
